source "https://supermarket.chef.io"

cookbook 'apt', '~> 2.6.0'
cookbook 'curl', '~> 2.0.1'
cookbook 'git', '~> 4.0.2'
cookbook 'nginx', '~> 2.7.4'
cookbook 'postgresql', '~> 3.4.14'
cookbook 'database', '~> 2.3.1'
cookbook 'sqlite', '~> 1.1.0'
cookbook 'nodejs', '~> 2.2.0'
cookbook 'libffi', 'git': 'https://github.com/americanhonors-cookbooks/libffi.git'